manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      # Additional modules containing boards/shields/custom code can be listed here as well.
      # See:
      # - https://zmk.dev/docs/features/modules
      # - https://docs.zephyrproject.org/3.5.0/develop/west/manifest.html#projects
  #  - name: gpeye
  #    url-base: https://github.com/GPeye
  projects:
    - name: gateway_sofle
      url: https://github.com/haram0909/eyelash-sofle-zmk
      revision: gateway #main
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0 #pin ZMK version
      import: app/west.yml
  self:
    path: boards
